<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'category_id' => 1,
                'name' => 'Kemeja Flanel Kotak-kotak',
                'sku' => 'KFLN001',
                'image' => 'back_assets/img/products/flanel-shirt.jpg',
                'description' => 'Kemeja flanel pria dengan motif kotak-kotak, bahan katun premium yang nyaman.',
                'unit' => 'pcs',
                'stock' => 50,
                'promo_label' => 'Flash Sale',
                'cost_price' => 75000.00,
                'selling_price' => 120000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Jaket Denim Vintage',
                'sku' => 'JDNM002',
                'image' => 'back_assets/img/products/denim-jacket.jpg',
                'description' => 'Jaket denim dengan desain vintage, cocok untuk gaya kasual.',
                'unit' => 'pcs',
                'stock' => 30,
                'promo_label' => 'Flash Sale',
                'cost_price' => 150000.00,
                'selling_price' => 250000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Celana Chino Slim Fit',
                'sku' => 'CCSF003',
                'image' => 'back_assets/img/products/chino-pants.jpg',
                'description' => 'Celana chino pria dengan potongan slim fit, bahan stretch yang nyaman.',
                'unit' => 'pcs',
                'stock' => 70,
                'promo_label' => 'Flash Sale',
                'cost_price' => 80000.00,
                'selling_price' => 145000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Gaun Malam Elegan',
                'sku' => 'GME004',
                'image' => 'back_assets/img/products/elegant-gown.jpg',
                'description' => 'Gaun malam wanita dengan detail brokat, cocok untuk acara formal.',
                'unit' => 'pcs',
                'stock' => 15,
                'promo_label' => 'Flash Sale',
                'cost_price' => 300000.00,
                'selling_price' => 550000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Sneakers Putih Klasik',
                'sku' => 'SPK005',
                'image' => 'back_assets/img/products/white-sneakers.jpg',
                'description' => 'Sepatu sneakers unisex warna putih, desain minimalis dan nyaman dipakai.',
                'unit' => 'pasang',
                'stock' => 100,
                'promo_label' => 'Bestseller',
                'cost_price' => 90000.00,
                'selling_price' => 175000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Kemeja Oxford Polos',
                'sku' => 'KOPL006',
                'image' => 'back_assets/img/products/oxford-shirt.jpg',
                'description' => 'Kemeja oxford polos pria, bahan tebal dan tidak mudah kusut.',
                'unit' => 'pcs',
                'stock' => 65,
                'promo_label' => 'Bestseller',
                'cost_price' => 70000.00,
                'selling_price' => 110000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Rok Plisket Panjang',
                'sku' => 'RPP007',
                'image' => 'back_assets/img/products/pleated-skirt.jpg',
                'description' => 'Rok plisket wanita dengan panjang semata kaki, bahan jatuh dan elegan.',
                'unit' => 'pcs',
                'stock' => 40,
                'promo_label' => 'Bestseller',
                'cost_price' => 60000.00,
                'selling_price' => 105000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Blazer Wanita Korea Style',
                'sku' => 'BWKS008',
                'image' => 'back_assets/img/products/korean-blazer.jpg',
                'description' => 'Blazer wanita dengan potongan ala Korea, cocok untuk tampilan formal dan casual.',
                'unit' => 'pcs',
                'stock' => 25,
                'promo_label' => 'Bestseller',
                'cost_price' => 120000.00,
                'selling_price' => 190000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Sandal Kulit Pria',
                'sku' => 'SKP009',
                'image' => 'back_assets/img/products/leather-sandals.jpg',
                'description' => 'Sandal pria bahan kulit asli, desain klasik dan tahan lama.',
                'unit' => 'pasang',
                'stock' => 55,
                'promo_label' => 'Limited Stock',
                'cost_price' => 110000.00,
                'selling_price' => 180000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Kaos Polos Cotton Combed 30s',
                'sku' => 'KPCC010',
                'image' => 'back_assets/img/products/plain-tshirt.jpg',
                'description' => 'Kaos polos unisex bahan cotton combed 30s, nyaman dan adem.',
                'unit' => 'pcs',
                'stock' => 200,
                'promo_label' => 'New Arrival',
                'cost_price' => 35000.00,
                'selling_price' => 60000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Jeans Wanita High Waist',
                'sku' => 'JWHW011',
                'image' => 'back_assets/img/products/high-waist-jeans.jpg',
                'description' => 'Celana jeans wanita model high waist, stretch dan nyaman dipakai.',
                'unit' => 'pcs',
                'stock' => 80,
                'promo_label' => null,
                'cost_price' => 95000.00,
                'selling_price' => 165000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Set Piyama Satin Wanita',
                'sku' => 'SPSW012',
                'image' => 'back_assets/img/products/satin-pajamas.jpg',
                'description' => 'Set piyama wanita bahan satin premium, halus dan nyaman untuk tidur.',
                'unit' => 'set',
                'stock' => 20,
                'promo_label' => 'Flash Sale',
                'cost_price' => 70000.00,
                'selling_price' => 135000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Tas Selempang Wanita',
                'sku' => 'TSW013',
                'image' => 'back_assets/img/products/ling-bag.jpg',
                'description' => 'Tas selempang wanita bahan kulit sintetis, minimalis dan fungsional.',
                'unit' => 'pcs',
                'stock' => 45,
                'promo_label' => null,
                'cost_price' => 80000.00,
                'selling_price' => 150000.00,
                'is_displayed' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
